apiVersion: apps/v1
kind: Deployment
metadata:
  name: natours
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: natours
      app.kubernetes.io/instance: natours
  template:
    metadata:
      labels:
        app.kubernetes.io/name: natours
        app.kubernetes.io/instance: natours
    spec:
      containers:
        - name: natours
          image: "${{FD_BUILT_DOCKER_IMAGE}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8099
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---

apiVersion: v1
kind: Service
metadata:
  name: natours
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8099
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: natours
    app.kubernetes.io/instance: natours
